import { User, Trip, MapLocation } from './types';

// Sample users
const demoUsers: User[] = [
    {
        id: 'demo-user-1',
        username: 'AlpineExplorer',
        email: 'alpine@demo.com',
        bio: 'Mountain lover. 200+ summits and counting. 🏔️',
        color: '#3b82f6',
        joinedAt: Date.now() - 90 * 86400000,
    },
    {
        id: 'demo-user-2',
        username: 'IslandWanderer',
        email: 'island@demo.com',
        bio: 'Chasing sunsets across volcanic islands. 🌋',
        color: '#f97316',
        joinedAt: Date.now() - 60 * 86400000,
    },
    {
        id: 'demo-user-3',
        username: 'NordicTrails',
        email: 'nordic@demo.com',
        bio: 'Fjords, forests, and freedom. 🇳🇴',
        color: '#10b981',
        joinedAt: Date.now() - 30 * 86400000,
    },
];

// Sample trips
const demoTrips: Trip[] = [
    {
        id: 'demo-trip-1',
        userId: 'demo-user-2',
        title: 'Tenerife Round Hike',
        description: 'A week-long circumnavigation of Tenerife through volcanic landscapes, cloud forests, and coastal cliffs. One of the most varied hiking routes in the Canaries.',
        startDate: Date.now() - 14 * 86400000,
        endDate: Date.now() - 7 * 86400000,
        visibility: 'public',
        difficulty: 'moderate',
        tags: ['hiking', 'island', 'coastal', 'mountain'],
        coverPhotoUrl: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?auto=format&fit=crop&q=80&w=800',
        likes: ['demo-user-1', 'demo-user-3'],
    },
    {
        id: 'demo-trip-2',
        userId: 'demo-user-1',
        title: 'Swiss Alps Haute Route',
        description: 'The classic Chamonix to Zermatt high-level traverse. 14 days of alpine meadows, glaciers, and some of the best mountain scenery on Earth.',
        startDate: Date.now() - 45 * 86400000,
        endDate: Date.now() - 31 * 86400000,
        visibility: 'public',
        difficulty: 'hard',
        tags: ['hiking', 'trekking', 'mountain', 'snow'],
        coverPhotoUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&q=80&w=800',
        likes: ['demo-user-2'],
    },
    {
        id: 'demo-trip-3',
        userId: 'demo-user-3',
        title: 'Norwegian Fjord Trail',
        description: 'Hiking through the heart of western Norway. Trolltunga, Preikestolen, and hidden fjord villages connected by ancient shepherd paths.',
        startDate: Date.now() - 25 * 86400000,
        endDate: Date.now() - 18 * 86400000,
        visibility: 'public',
        difficulty: 'moderate',
        tags: ['hiking', 'trekking', 'coastal', 'camping'],
        coverPhotoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=800',
        likes: ['demo-user-1', 'demo-user-2'],
    },
    {
        id: 'demo-trip-4',
        userId: 'demo-user-1',
        title: 'Dolomites Via Ferrata',
        description: 'Iron paths through the pale mountains. Three days of exposed ridges, WW1 tunnels, and rifugio dinners with views.',
        startDate: Date.now() - 60 * 86400000,
        endDate: Date.now() - 57 * 86400000,
        visibility: 'public',
        difficulty: 'expert',
        tags: ['hiking', 'mountain', 'trekking'],
        coverPhotoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
        likes: ['demo-user-3'],
    },
];

// Sample locations
const demoLocations: MapLocation[] = [
    // --- Tenerife Round Hike ---
    {
        id: 'demo-loc-1',
        tripId: 'demo-trip-1',
        userId: 'demo-user-2',
        coords: { lat: 28.2916, lng: -16.6291 },
        title: 'Anaga Cloud Forest',
        comment: 'Walking through clouds in a prehistoric forest. Absolutely magical. 🌿',
        photoUrl: 'https://images.unsplash.com/photo-1440342359743-84fcb8c21c7e?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 14 * 86400000,
        type: 'adventure',
    },
    {
        id: 'demo-loc-2',
        tripId: 'demo-trip-1',
        userId: 'demo-user-2',
        coords: { lat: 28.2723, lng: -16.6424 },
        title: 'Teide Summit View',
        comment: 'Above the clouds at 3,718m. Spain\'s highest point! 🏔️',
        photoUrl: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 12 * 86400000,
        type: 'summit',
    },
    {
        id: 'demo-loc-3',
        tripId: 'demo-trip-1',
        userId: 'demo-user-2',
        coords: { lat: 28.1400, lng: -16.7300 },
        title: 'Los Gigantes Cliffs',
        comment: 'Massive vertical cliffs dropping straight into the ocean. Jaw-dropping. 🌊',
        photoUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 10 * 86400000,
        type: 'viewpoint',
    },
    {
        id: 'demo-loc-4',
        tripId: 'demo-trip-1',
        userId: 'demo-user-2',
        coords: { lat: 28.0500, lng: -16.5700 },
        title: 'Coastal Trail Camp',
        comment: 'Wild-camping above the sea with a sky full of stars ⛺✨',
        photoUrl: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 9 * 86400000,
        type: 'camp',
    },

    // --- Swiss Alps Haute Route ---
    {
        id: 'demo-loc-5',
        tripId: 'demo-trip-2',
        userId: 'demo-user-1',
        coords: { lat: 45.9237, lng: 7.8694 },
        title: 'Aletsch Glacier Viewpoint',
        comment: 'Longest glacier in the Alps. The scale is unreal. ❄️',
        photoUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 40 * 86400000,
        type: 'viewpoint',
    },
    {
        id: 'demo-loc-6',
        tripId: 'demo-trip-2',
        userId: 'demo-user-1',
        coords: { lat: 46.0207, lng: 7.7487 },
        title: 'Alpine Meadow Rest',
        comment: 'Lunch with the cows. Swiss chocolate never tasted better. ☕🍫',
        photoUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 38 * 86400000,
        type: 'chill',
    },
    {
        id: 'demo-loc-7',
        tripId: 'demo-trip-2',
        userId: 'demo-user-1',
        coords: { lat: 46.0176, lng: 7.7468 },
        title: 'Matterhorn First Sight',
        comment: 'That iconic silhouette. No photo does it justice. 🏔️',
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 35 * 86400000,
        type: 'summit',
    },

    // --- Norwegian Fjord Trail ---
    {
        id: 'demo-loc-8',
        tripId: 'demo-trip-3',
        userId: 'demo-user-3',
        coords: { lat: 60.1241, lng: 6.7440 },
        title: 'Trolltunga',
        comment: 'Stood on the troll\'s tongue 700m above the fjord. Knees were shaking! 😱',
        photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 24 * 86400000,
        type: 'viewpoint',
    },
    {
        id: 'demo-loc-9',
        tripId: 'demo-trip-3',
        userId: 'demo-user-3',
        coords: { lat: 58.9863, lng: 6.1886 },
        title: 'Preikestolen',
        comment: 'The Pulpit Rock at sunrise. Worth every step of the 4h hike. 🌅',
        photoUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 22 * 86400000,
        type: 'viewpoint',
    },
    {
        id: 'demo-loc-10',
        tripId: 'demo-trip-3',
        userId: 'demo-user-3',
        coords: { lat: 60.8600, lng: 6.9800 },
        title: 'Fjord Kayak Launch',
        comment: 'Paddled into the fjord at dawn. Perfectly still water. 🛶',
        photoUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 20 * 86400000,
        type: 'lake',
    },
    {
        id: 'demo-loc-11',
        tripId: 'demo-trip-3',
        userId: 'demo-user-3',
        coords: { lat: 60.4700, lng: 6.5400 },
        title: 'Mountain Shelter Stay',
        comment: 'A cozy DNT cabin in the middle of nowhere. Hot cocoa and rain on the roof. 🛖',
        photoUrl: 'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 19 * 86400000,
        type: 'shelter',
    },

    // --- Dolomites Via Ferrata ---
    {
        id: 'demo-loc-12',
        tripId: 'demo-trip-4',
        userId: 'demo-user-1',
        coords: { lat: 46.5861, lng: 11.9567 },
        title: 'Via Ferrata Start',
        comment: 'Clipping in at the trailhead. Let\'s go! 🥾⛰️',
        photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 59 * 86400000,
        type: 'trailhead',
    },
    {
        id: 'demo-loc-13',
        tripId: 'demo-trip-4',
        userId: 'demo-user-1',
        coords: { lat: 46.5300, lng: 11.9300 },
        title: 'Tre Cime Panorama',
        comment: 'The three peaks glowing in golden hour. Photography heaven. 📸',
        photoUrl: 'https://images.unsplash.com/photo-1440342359743-84fcb8c21c7e?auto=format&fit=crop&q=80&w=600',
        timestamp: Date.now() - 58 * 86400000,
        type: 'viewpoint',
    },
];

export const seedDemoData = (): { users: User[]; trips: Trip[]; locations: MapLocation[] } => {
    return {
        users: demoUsers,
        trips: demoTrips,
        locations: demoLocations,
    };
};
